### PR TITLE
README file added with required docu

### PR DESCRIPTION
**Pull request by ritam077**

### CODE REVIEW

**Comment by ritam077** [comment]
Hello besically can you assign me to add a java project...i can do it.please

**Comment by ritam077** [comment]
or else...please dont spam it...i will close it if you have any problem

**Comment by harshit0571** [comment]
hi @ritam077 , we are only accepting changes in the main readme file.
You can contribute by adding a hacktoberfest open source repo link in the readme.

dont add folder in it.

**Comment by harshit0571** [comment]
Screenshot from 2022-10-08 22-28-46

only make changes here!

**Comment by harshit0571** [comment]
you can add repos that you have contributed to

**Pull request closed without merging**
